/**
 * Onboard skill — intelligent project scanner.
 *
 * Scans a new codebase, identifies stack/architecture/patterns,
 * and writes a persistent project brief that loads as context
 * in all future sessions.
 */

import { registerBundledSkill } from "../registry.js"

const ONBOARD_PROMPT = `# Onboard: Project Intelligence Scanner

You are scanning this project for the first time. Your job is to understand its DNA and write a persistent project brief that will give future sessions instant context.

## Phase 1 — Reconnaissance

Scan the project root to understand the structure. Read these files (if they exist):
- \`package.json\`, \`pyproject.toml\`, \`Cargo.toml\`, \`go.mod\`, \`pom.xml\` — dependencies & scripts
- \`tsconfig.json\`, \`vite.config.*\`, \`next.config.*\`, \`webpack.config.*\` — build config
- \`.eslintrc*\`, \`.prettierrc*\`, \`biome.json\` — code style
- \`Dockerfile\`, \`docker-compose.yml\` — infrastructure
- \`CI/CD\` configs: \`.github/workflows/\`, \`.gitlab-ci.yml\`, \`Jenkinsfile\`
- \`README.md\` — project description

Also run:
- \`ls\` or \`dir\` on the root to see the directory layout
- \`git log --oneline -20\` to understand recent activity
- \`git remote -v\` to identify the repository

## Phase 2 — Analysis

From what you found, determine:

1. **Stack**: Language(s), framework(s), runtime, package manager
2. **Architecture**: Monorepo vs single-pkg, frontend/backend split, microservices, etc.
3. **Build System**: How to build, test, run dev server, lint
4. **Key Directories**: What lives where (src/, lib/, tests/, docs/)
5. **Coding Patterns**: Naming conventions, error handling style, state management
6. **Dependencies**: Key external libraries and what they're used for (top 10)
7. **Development Workflow**: Branch strategy, CI/CD, deployment

## Phase 3 — Write Project Brief

Create the file \`.opencode/PROJECT.md\` with this structure:

\`\`\`markdown
# Project Brief: <project name>

> Auto-generated by Xethryon /onboard — last updated: <date>

## Overview
<1-2 sentence description of what this project is>

## Stack
- **Language**: <e.g., TypeScript 5.x>
- **Framework**: <e.g., Next.js 14>
- **Runtime**: <e.g., Node 20, Bun 1.x>
- **Package Manager**: <e.g., pnpm>

## Architecture
<Brief description of how the project is structured>

## Quick Commands
| Action | Command |
|--------|---------|
| Dev    | \`npm run dev\` |
| Build  | \`npm run build\` |
| Test   | \`npm test\` |
| Lint   | \`npm run lint\` |

## Key Directories
- \`src/\` — <description>
- \`tests/\` — <description>

## Important Patterns
<Coding conventions, architecture decisions, gotchas>

## Dependencies (Key)
| Package | Purpose |
|---------|---------|
| <name> | <what it does> |

## Notes
<Anything else important for future sessions>
\`\`\`

## Phase 4 — Verify

- Re-read the generated \`PROJECT.md\` and make sure it's accurate
- If anything seems wrong or incomplete, fix it
- Report what you found to the user with a brief summary

## Rules
- Be accurate — don't guess if you can check
- Be concise — this file will be read at the start of every session
- Focus on actionable context — what would a new developer need to know?
- Don't include sensitive data (API keys, passwords) in the brief
`

export function registerOnboardSkill(): void {
  registerBundledSkill({
    name: "onboard",
    description: "Scan this project and generate a persistent brief for instant context in future sessions.",
    userInvocable: true,
    subtask: false,
    async getPrompt(args) {
      const parts: string[] = [ONBOARD_PROMPT.trimStart()]
      if (args) {
        parts.push(`## Additional Focus\n\nThe user wants you to pay special attention to: ${args}`)
      }
      return parts.join("\n\n")
    },
  })
}
